apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
        - name: chatbot
          image: chatbot.azurecr.io/chatbot-ai-app:v1
          ports:
            - containerPort: 80
            resources:
              limits:
                memory: "2Gi"
                cpu: "1"
              requests:
                memory: "1Gi"
                cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata:
  name: chatbot-service
spec:
  type: LoadBalancer
  selector:
    app: chatbot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80