env:
- name: LUIS_KEY
  valueFrom:
    secretKeyRef:
      name: luis
      key: luis-key

# Add network policies 

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: chatbot-network-policy
spec:
  podSelector:
    matchLabels:
      app: chatbot
  ingress:
  - from: []

